<?php
/**
 * CYN Tourism - English Language File
 * Complete translations for the tourism management system
 * 
 * @package CYN_Tourism
 * @version 1.0.0
 */

return [
    // General
    'welcome' => 'Welcome',
    'hello' => 'Hello',
    'logout' => 'Logout',
    'login' => 'Login',
    'register' => 'Register',
    'save' => 'Save',
    'cancel' => 'Cancel',
    'delete' => 'Delete',
    'edit' => 'Edit',
    'view' => 'View',
    'create' => 'Create',
    'update' => 'Update',
    'search' => 'Search',
    'filter' => 'Filter',
    'clear' => 'Clear',
    'back' => 'Back',
    'next' => 'Next',
    'previous' => 'Previous',
    'submit' => 'Submit',
    'close' => 'Close',
    'yes' => 'Yes',
    'no' => 'No',
    'ok' => 'OK',
    'error' => 'Error',
    'success' => 'Success',
    'warning' => 'Warning',
    'info' => 'Info',
    'loading' => 'Loading...',
    'no_results' => 'No results found',
    'required' => 'Required',
    'optional' => 'Optional',
    'actions' => 'Actions',
    'all' => 'All',
    'select' => 'Select',
    'select_all' => 'Select All',
    'deselect_all' => 'Deselect All',
    'print' => 'Print',
    'download' => 'Download',
    'send' => 'Send',
    'refresh' => 'Refresh',
    'details' => 'Details',
    'more' => 'More',
    'less' => 'Less',
    'show' => 'Show',
    'hide' => 'Hide',
    'expand' => 'Expand',
    'collapse' => 'Collapse',
    
    // Navigation
    'main_menu' => 'Main Menu',
    'dashboard' => 'Dashboard',
    'transfers' => 'Transfers',
    'transfer_calendar' => 'Transfer Calendar',
    'transfer_voucher' => 'Transfer Voucher',
    'transfer_invoice' => 'Transfer Invoice',
    'hotels' => 'Hotels',
    'hotel_calendar' => 'Hotel Calendar',
    'hotel_voucher' => 'Hotel Voucher',
    'hotel_invoice' => 'Hotel Invoice',
    'tours' => 'Tours',
    'tour_calendar' => 'Tour Calendar',
    'tour_voucher' => 'Tour Voucher',
    'finance' => 'Finance',
    'receipt' => 'Receipt',
    'receipt_dashboard' => 'Receipt Dashboard',
    'invoice_list' => 'Invoice List',
    'documents' => 'Documents',
    'letterhead' => 'Letterhead',
    'management' => 'Management',
    'partners' => 'Partners',
    'vehicles' => 'Vehicles',
    'drivers' => 'Drivers',
    'tour_guides' => 'Tour Guides',
    'users' => 'Users',
    'profile' => 'Profile',
    'reports' => 'Reports',
    'settings' => 'Settings',
    'system_settings' => 'System Settings',
    'backup_restore' => 'Backup & Restore',
    'logs' => 'System Logs',
    'maintenance_mode' => 'Maintenance Mode',
    
    // Dashboard
    'todays_transfers' => "Today's Transfers",
    'todays_tours' => "Today's Tours",
    'pending_invoices' => 'Pending Invoices',
    'overdue_invoices' => 'Overdue Invoices',
    'monthly_revenue' => 'Monthly Revenue',
    'pending_amount' => 'Pending Amount',
    'total_partners' => 'Total Partners',
    'quick_actions' => 'Quick Actions',
    'total_statistics' => 'Total Statistics',
    'upcoming_bookings' => 'Upcoming Bookings',
    'recent_activity' => 'Recent Activity',
    'total_transfers' => 'Total Transfers',
    'total_hotels' => 'Total Hotels',
    'total_tours' => 'Total Tours',
    'total_invoices' => 'Total Invoices',
    'welcome_back' => 'Welcome back',
    'last_login' => 'Last login',
    'notifications' => 'Notifications',
    'view_all' => 'View All',
    'mark_as_read' => 'Mark as Read',
    
    // Forms - Common
    'voucher_no' => 'Voucher No',
    'invoice_no' => 'Invoice No',
    'receipt_no' => 'Receipt No',
    'company_name' => 'Company Name',
    'customer_name' => 'Customer Name',
    'customer_phone' => 'Customer Phone',
    'hotel_name' => 'Hotel Name',
    'date' => 'Date',
    'time' => 'Time',
    'status' => 'Status',
    'notes' => 'Notes',
    'created_at' => 'Created At',
    'updated_at' => 'Updated At',
    'created_by' => 'Created By',
    'description' => 'Description',
    'reference' => 'Reference',
    'priority' => 'Priority',
    
    // Transfer Form
    'transfer_type' => 'Transfer Type',
    'one_way' => 'One Way',
    'round_trip' => 'Round Trip',
    'arrival_return' => 'Arrival - Return',
    'arrival_only' => 'Arrival Only',
    'return_only' => 'Return Only',
    'pickup_location' => 'Pickup Location',
    'dropoff_location' => 'Dropoff Location',
    'pickup_date' => 'Pickup Date',
    'pickup_time' => 'Pickup Time',
    'return_date' => 'Return Date',
    'return_time' => 'Return Time',
    'flight_number' => 'Flight Number',
    'total_pax' => 'Total Passengers',
    'passengers' => 'Passengers',
    'passenger_list' => 'Passenger List',
    'add_passenger' => 'Add Passenger',
    'remove_passenger' => 'Remove Passenger',
    'vehicle' => 'Vehicle',
    'driver' => 'Driver',
    
    // Hotel Form
    'check_in_date' => 'Check-in Date',
    'check_out_date' => 'Check-out Date',
    'nights' => 'Nights',
    'room_count' => 'Room Count',
    'room_type' => 'Room Type',
    'board' => 'Board',
    'adult' => 'Adult',
    'child' => 'Child',
    'infant' => 'Infant',
    'guest_count' => 'Guest Count',
    'single_room' => 'Single Room',
    'double_room' => 'Double Room',
    'triple_room' => 'Triple Room',
    'suite' => 'Suite',
    
    // Tour Form
    'tour_name' => 'Tour Name',
    'tour_date' => 'Tour Date',
    'duration' => 'Duration',
    'tour_guide' => 'Tour Guide',
    'customers' => 'Customers',
    'tour_type' => 'Tour Type',
    'meeting_point' => 'Meeting Point',
    'meeting_time' => 'Meeting Time',
    
    // Invoice Form
    'amount' => 'Amount',
    'currency' => 'Currency',
    'total_amount' => 'Total Amount',
    'price_per_night' => 'Price per Night',
    'transfer_price' => 'Transfer Price',
    'starting_point' => 'Starting Point',
    'destination' => 'Destination',
    'subtotal' => 'Subtotal',
    'tax' => 'Tax',
    'discount' => 'Discount',
    'due_date' => 'Due Date',
    'payment_status' => 'Payment Status',
    
    // Receipt Form
    'reason' => 'Reason',
    'payment_method' => 'Payment Method',
    'received_by' => 'Received By',
    'remaining_amount' => 'Remaining Amount',
    'cash' => 'Cash',
    'bank_transfer' => 'Bank Transfer',
    'credit_card' => 'Credit Card',
    'check' => 'Check',
    
    // Status
    'pending' => 'Pending',
    'confirmed' => 'Confirmed',
    'completed' => 'Completed',
    'cancelled' => 'Cancelled',
    'paid' => 'Paid',
    'overdue' => 'Overdue',
    'active' => 'Active',
    'inactive' => 'Inactive',
    'maintenance' => 'Maintenance',
    'draft' => 'Draft',
    'sent' => 'Sent',
    
    // Partners
    'partner_management' => 'Partner Management',
    'new_partner' => 'New Partner',
    'edit_partner' => 'Edit Partner',
    'contact_person' => 'Contact Person',
    'email' => 'Email',
    'phone' => 'Phone',
    'address' => 'Address',
    'payment_terms' => 'Payment Terms',
    'credit_limit' => 'Credit Limit',
    'total_partners' => 'Total Partners',
    'partner_type' => 'Partner Type',
    'supplier' => 'Supplier',
    'customer' => 'Customer',
    'both' => 'Both',
    
    // Vehicles
    'vehicle_management' => 'Vehicle Management',
    'new_vehicle' => 'New Vehicle',
    'edit_vehicle' => 'Edit Vehicle',
    'plate_number' => 'Plate Number',
    'vehicle_type' => 'Vehicle Type',
    'brand' => 'Brand',
    'model' => 'Model',
    'year' => 'Year',
    'capacity' => 'Capacity',
    'sedan' => 'Sedan',
    'minivan' => 'Minivan',
    'van' => 'Van',
    'midibus' => 'Midibus',
    'bus' => 'Bus',
    'luxury' => 'Luxury',
    'total_vehicles' => 'Total Vehicles',
    
    // Drivers
    'driver_management' => 'Driver Management',
    'new_driver' => 'New Driver',
    'edit_driver' => 'Edit Driver',
    'first_name' => 'First Name',
    'last_name' => 'Last Name',
    'license_number' => 'License Number',
    'license_expiry' => 'License Expiry',
    'languages' => 'Languages',
    'total_drivers' => 'Total Drivers',
    'driver_status' => 'Driver Status',
    'available' => 'Available',
    'on_duty' => 'On Duty',
    'off_duty' => 'Off Duty',
    
    // Tour Guides
    'guide_management' => 'Tour Guide Management',
    'new_guide' => 'New Guide',
    'edit_guide' => 'Edit Guide',
    'guide_license' => 'Guide License',
    'specialties' => 'Specialties',
    'total_guides' => 'Total Guides',
    
    // Messages
    'saved_successfully' => 'Saved successfully',
    'updated_successfully' => 'Updated successfully',
    'deleted_successfully' => 'Deleted successfully',
    'error_occurred' => 'An error occurred',
    'confirm_delete' => 'Are you sure you want to delete?',
    'no_data_found' => 'No data found',
    'create_first' => 'Create your first entry',
    'operation_successful' => 'Operation completed successfully',
    'operation_failed' => 'Operation failed',
    'please_wait' => 'Please wait...',
    'processing' => 'Processing...',
    
    // Letterhead
    'document_type' => 'Document Type',
    'letter' => 'Letter',
    'proposal' => 'Proposal',
    'confirmation' => 'Confirmation',
    'other' => 'Other',
    'recipient_name' => 'Recipient Name',
    'recipient_company' => 'Recipient Company',
    'recipient_address' => 'Recipient Address',
    'subject_title' => 'Subject/Title',
    'letter_content' => 'Letter Content',
    'letter_date' => 'Letter Date',
    'reference_no' => 'Reference No',
    'preview' => 'Preview',
    'print_pdf' => 'Print / PDF',
    
    // Export
    'export_excel' => 'Export to Excel',
    'export_pdf' => 'Export to PDF',
    'date_range' => 'Date Range',
    'start_date' => 'Start Date',
    'end_date' => 'End Date',
    
    // Email
    'email_settings' => 'Email Settings',
    'smtp_host' => 'SMTP Host',
    'smtp_port' => 'SMTP Port',
    'smtp_user' => 'SMTP Username',
    'smtp_pass' => 'SMTP Password',
    'smtp_encryption' => 'Encryption',
    'email_from' => 'From Email',
    'email_from_name' => 'From Name',
    'email_signature' => 'Email Signature',
    'test_email' => 'Test Email',
    
    // Footer
    'all_rights_reserved' => 'All Rights Reserved',
    'privacy_policy' => 'Privacy Policy',
    'terms_conditions' => 'Terms & Conditions',
    'contact_us' => 'Contact Us',
    'tursab_license' => 'TURSAB License No',
    
    // Validation Messages
    'field_required' => 'This field is required',
    'invalid_email' => 'Please enter a valid email address',
    'invalid_phone' => 'Please enter a valid phone number',
    'invalid_date' => 'Please enter a valid date',
    'password_too_short' => 'Password must be at least :min characters',
    'password_mismatch' => 'Passwords do not match',
    'invalid_file_type' => 'Invalid file type. Allowed types: :types',
    'file_too_large' => 'File is too large. Maximum size: :size',
    'invalid_csrf_token' => 'Invalid security token. Please refresh the page and try again.',
    'session_expired' => 'Your session has expired. Please login again.',
    
    // Pagination
    'showing' => 'Showing',
    'to' => 'to',
    'of' => 'of',
    'entries' => 'entries',
    'page' => 'Page',
    'per_page' => 'per page',
    'first' => 'First',
    'last' => 'Last',
    
    // Login/Auth
    'remember_me' => 'Remember Me',
    'forgot_password' => 'Forgot Password?',
    'reset_password' => 'Reset Password',
    'password' => 'Password',
    'confirm_password' => 'Confirm Password',
    'current_password' => 'Current Password',
    'new_password' => 'New Password',
    'login_failed' => 'Invalid email or password',
    'account_locked' => 'Account locked. Please try again later.',
    'password_reset_sent' => 'Password reset instructions sent to your email',
    
    // Error Pages
    'page_not_found' => 'Page Not Found',
    'page_not_found_message' => 'The page you are looking for does not exist.',
    'access_denied' => 'Access Denied',
    'access_denied_message' => 'You do not have permission to access this page.',
    'server_error' => 'Server Error',
    'server_error_message' => 'Something went wrong. Please try again later.',
    'maintenance_title' => 'Under Maintenance',
    'maintenance_message' => 'We are currently performing maintenance. Please check back later.',
    'go_home' => 'Go to Homepage',
    'go_back' => 'Go Back',
    
    // Backup
    'create_backup' => 'Create Backup',
    'download_backup' => 'Download Backup',
    'restore_backup' => 'Restore Backup',
    'delete_backup' => 'Delete Backup',
    'backup_created' => 'Backup created successfully',
    'backup_restored' => 'Backup restored successfully',
    'backup_deleted' => 'Backup deleted successfully',
    'backup_failed' => 'Backup failed',
    'restore_failed' => 'Restore failed',
    'confirm_restore' => 'Are you sure you want to restore this backup? All current data will be replaced.',
    'last_backup' => 'Last Backup',
    'never' => 'Never',
    'auto_backup' => 'Automatic Backup',
    'daily' => 'Daily',
    'weekly' => 'Weekly',
    'monthly' => 'Monthly',
    
    // Logs
    'system_logs' => 'System Logs',
    'activity_logs' => 'Activity Logs',
    'error_logs' => 'Error Logs',
    'clear_logs' => 'Clear Logs',
    'log_level' => 'Log Level',
    'log_date' => 'Log Date',
    'log_message' => 'Message',
    'no_logs_found' => 'No logs found',
    
    // Users
    'user_management' => 'User Management',
    'new_user' => 'New User',
    'edit_user' => 'Edit User',
    'role' => 'Role',
    'admin' => 'Administrator',
    'manager' => 'Manager',
    'staff' => 'Staff',
    'last_active' => 'Last Active',
    
    // File Upload
    'upload_file' => 'Upload File',
    'drag_drop' => 'Drag and drop files here',
    'or_click' => 'or click to browse',
    'max_file_size' => 'Maximum file size',
    'allowed_types' => 'Allowed file types',
];
